# Book settings

title: Single-cell analysis Tutorial
author: Theislab
logo: logo.png

exclude_patterns:
  -  _build
  - Thumbs.db
  - .DS_Store
  - "**.ipynb_checkpoints"
  - "figures"
  - "datasets"
  - "README.md"

# Parse and render settings
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution

# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/theislab/extended-single-cell-best-practices
  path_to_book: book
  branch: master 

# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar         : false
  use_edit_page_button        : true
  use_repository_button       : true
  use_issues_button           : true
  favicon: _static/favicon.ico
  comments:
    hypothesis: true
  extra_footer: |
    <div>
      Brought to you by
      <a href="https://github.com/theislab">Theis Lab</a>,
      with many thanks to the single-cell community as a whole!
    </div>
