# Book settings

title: Single-cell analysis Tutorial
author: Theislab
logo: logo.png

# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/theislab/extended-single-cell-best-practices
  path_to_book: book
  branch: master 

# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
